version: '3'
services:
  web:
    image: nginx:latest
    volumes:
    - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    - "./public:/var/www/html"
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=localhost
    restart: always
    depends_on:
    - php
  php:
    #image: php:7.2-fpm
    build:
      context: .
      dockerfile: ./etc/Dockerfile
    restart: always
    volumes:
    - "./:/var/www/html"
    ports:
    - "9090:9000"
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
    - 11212:11211